ホーム画面のライブ部分のコンテンツのデザイン実装
and-period/furumaru pull request #965
Opened 2023-05-25 14:57 UTC by wf-yamaday

## やったこと

- ホーム画面のライブ部分のコンテンツのデザインを実装した。

## スクリーンショット

## リファレンス

## 残タスク

## 備考

2023-05-25 16:45 UTC, hamachans requested changes
実装ありがとう！

2023-05-25 16:45 UTC, hamachans commented on web/user/src/public/img/live/4.png
おばあちゃんの笑顔素敵だね

2023-05-25 16:45 UTC, hamachans commented on web/user/src/constants/mock/live.ts
> +    title: '［大崎上島マルシェ］瀬戸内海の島の美味しいものを紹介します！',
これって文字数が多くなったらどうなる、枠はみ出そうだったら、最後に「...」
みたいに出せるかな、
ex ) ［大崎上島マルシェ］瀬戸内海の島の美味しいものを紹介します。ぜひみなさん見て...
的な？

2023-05-25 16:46 UTC, hamachans approved these changes

2023-05-26 13:58 UTC, wf-yamaday commented on web/user/src/constants/mock/live.ts
> +    title: '［大崎上島マルシェ］瀬戸内海の島の美味しいものを紹介します！',
出せるので対応しますね

2023-05-26 14:02 UTC, wf-yamaday commented on web/user/src/constants/mock/live.ts
> +    title: '［大崎上島マルシェ］瀬戸内海の島の美味しいものを紹介します！',
ちなみに今は枠をはみ出すことはなくて、枠そのものが大きくなります。

2023-05-26 15:00 UTC, merged